insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E1', 'B11', 'D21', to_date('2015-09-05', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E2', 'B12', 'D26', to_date('2019-03-20', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E3', 'B11', 'D28', to_date('2016-11-03', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E4', 'B11', 'D21', to_date('2018-04-08', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E5', 'B12', 'D22', to_date('2016-09-06', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E6', 'B13', 'D23', to_date('2016-04-02', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E7', 'B14', 'D23', to_date('2017-02-08', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E8', 'B13', 'D26', to_date('2016-01-22', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E9', 'B12', 'D28', to_date('2018-07-31', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E10', 'B12', 'D24', to_date('2018-09-26', 'YYYY-MM-DD'), 'Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E11', 'B15', 'D26', to_date('2018-12-07', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E12', 'B14', 'D24', to_date('2016-12-25', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E13', 'B13', 'D27', to_date('2016-04-12', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E14', 'B14', 'D27', to_date('2017-06-17', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E15', 'B15', 'D28', to_date('2018-05-10', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E16', 'B16', 'D21', to_date('2019-01-12', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E17', 'B16', 'D21', to_date('2017-07-03', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E18', 'B18', 'D23', to_date('2016-03-23', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E19', 'B19', 'D22', to_date('2018-12-31', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E20', 'B20', 'D25', to_date('2018-03-30', 'YYYY-MM-DD'), 'Teller');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E21', 'B12', 'D26', to_date('2018-07-31', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E22', 'B12', 'D27', to_date('2015-07-21', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E23', 'B13', 'D28', to_date('2018-02-17', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E24', 'B18', 'D26', to_date('2019-04-09', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E25', 'B18', 'D25', to_date('2015-12-26', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E26', 'B20', 'D27', to_date('2017-01-02', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E27', 'B17', 'D28', to_date('2018-11-15', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E28', 'B16', 'D24', to_date('2017-05-24', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E29', 'B15', 'D26', to_date('2018-12-15', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E30', 'B15', 'D21', to_date('2019-03-25', 'YYYY-MM-DD'), 'Accountant');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E31', 'B19', 'D23', to_date('2018-11-25', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E32', 'B14', 'D24', to_date('2016-11-02', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E33', 'B13', 'D26', to_date('2019-03-31', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E34', 'B11', 'D24', to_date('2016-05-21', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E35', 'B17', 'D28', to_date('2017-11-13', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E36', 'B17', 'D24', to_date('2017-01-16', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E37', 'B19', 'D25', to_date('2017-07-31', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E38', 'B20', 'D26', to_date('2016-11-08', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E39', 'B19', 'D21', to_date('2015-10-20', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E40', 'B15', 'D22', to_date('2018-01-24', 'YYYY-MM-DD'), 'Relationship Manager');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E41', 'B16', 'D23', to_date('2018-10-02', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E42', 'B14', 'D26', to_date('2015-10-24', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E43', 'B11', 'D27', to_date('2016-10-20', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E44', 'B18', 'D27', to_date('2017-10-15', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E45', 'B17', 'D24', to_date('2015-10-16', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E46', 'B19', 'D25', to_date('2018-06-08', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E47', 'B20', 'D25', to_date('2016-12-08', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E48', 'B14', 'D21', to_date('2016-03-07', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E49', 'B19', 'D22', to_date('2018-06-19', 'YYYY-MM-DD'), 'Auditor');
insert into employee (employee_id, IFSC_code, dept_id, join_date, employee_position) values ('E50', 'B17', 'D24', to_date('2016-10-23', 'YYYY-MM-DD'), 'Auditor');

